apiVersion: batch/v1
kind: Job
metadata:
  name: busybox
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 86400
  activeDeadlineSeconds: 30
  template:
    spec:
      restartPolicy: Never
      runtimeClassName: gvisor
      containers:
      - name: busybox
        image: busybox
        command: ["sleep",  "120"]
        env:
        - name: TEST
          value: VALUE
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 10m
            memory: 50Mi
        securityContext:
          runAsNonRoot: true
          runAsUser: 33
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop: ["all"]
