apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simple-admission
  name: simple-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-admission
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-admission
    spec:
      containers:
      - name: simple-admission
        image: fdns/simple-admission:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: admission-certs
          mountPath: /certs
          readOnly: true
        resources:
          requests:
            memory: 50Mi
            cpu: 25m
          limits:
            memory: 100Mi
            cpu: 100m
      volumes:
      - name: admission-certs
        secret:
          secretName: admission-certs
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-admission
  name: simple-admission
spec:
  ports:
  - name: 443-8443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: simple-admission
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: admission-certs
data:
  server-key.pem: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbnJzNzFwUENHQjhqZzE5NDVqa1ZLaUdVb2tkdHgrMVNBVkVqeUIraUlTREtSYUp1CmlQWkI5bUFkU3pNTXpURVVqblFZVDZTN2p5QkVYY00xV2RNTzdOVGI4dTFrWklvajlxZEdILy9UODBNeENzcDAKemJaWUUweVdRUTJ4aFRTRFFiUjE4clBkS2NjRk9IQUQvKy9XWmp4ZG96S1RMeDRUSzAvN0lGMXJ6dnNzZHZZWApZYk1tT05sUWNQeHg5YmFOV3hpZEVsUzNDTzBQaDhqK1pBUW1JOXM5T0JNVjZUcFFBbnZhUDVhbVBzMXArREhOCnh2NmpLWHhmckdRWk5UR2g3OGpmL1pZTCthNER5eDZhLysxNGtrRXBmUllkTkdCZGlLWGF5Q09RS3AvNmp2c2kKRXRSQVpKLy9BclJzVS90NlZIbE9NZXEyTHljWjNxRk1vMnYwL3dJREFRQUJBb0lCQUhMbzhNVENhdnl6Ymk0bwo2NGtmUWVjaU1FdmFrZXJ1THpPczNjNSt1QXhyaElNc3VBQ0c1ZkhLV3VxWnBtYlZaU0JMZzE0RXo1TXB0TlI4CkFSOXAzNkFyNko3UXBLRDBNRnpiYzdTdXEyMnI4dER4QitYMFg0WjVKejBwQUo2Q0NaT0RaTyt5cmlVVVl2OGMKZUlqTHc5WjNWUUpVRnFGQmtIY0dpN0krYjFHQzk5Yy9IYmlWQU1JS1BNMDR6WDdYTzE2Rk00Mk9qZmJWY2VYVgpkT0Rkd01sK3hKMFpCWHVtUTIxVkNaNzAzdTQ3Z08xTEZGVFp3UkRUV0U3RmhoRUYwaWttWkhqTlkwQThtN1BpCmd4WlJmTkh6dFY2dVE1N05VWFExVm9PTjdzdU9pSmlhUVhsT25ZUERCbWJ2R3BzVHJnL245UlRHaFRseGkxejAKWUV4M1JpRUNnWUVBMDJxRXNkNmVLSHJMZ3RUVVpKVjBldzRiN2UwSHRkZkU3RFNhVEZtM0RCeHJiN2pablR3dAp4MWtEM0xoV0N5TUUyZlg2TTd4bE1EYUQ3dzFlRmNGanRJT2p4UktPM2tMTkpteEY1TVBJWHVlRTRlb1N5Tm9hCkZTeHM2TGxtaXFEZzg1ZVNpc0RUeTBLNHlsR01iK3N6WHI5RzRCQ2NaNFAwTlBUUzIzYW9nSFVDZ1lFQXdEUjgKVllVNXd3LzlYT2VhYUYrUVFZbUdkZ1YwT1dNMk5OVTV1MFB2b3d0TmM4YVhmdjhMb2QrZWFoSXJ2d2N1QjhVegplSFZHVExZSjJnQlBzY254c2dmWUc4NnQyRWRicHhYeW1JZ2pBdVpIOHZSbUphOEcrakxnRW40Vm04c1NZWmw3CjZ5Y0IzZWdmSTE4aG9kVjJpY1NhelVsL0NCenRsZkt0dHdrY01TTUNnWUFzQytjMWY2SUg0UDJCZG9JQnFybW4KNFpxa0NWd3Y0SkpnZTkwaHh4ZEI2TEhoaHV1ZnZLZjAvbkMxalpvdm04NG84dng3eHVaMkV3V055b1V0bHlzRQpzdUJ0OEozZlpKK0ZQODJZQ2NvM0s1a2QwRHkxcCtzRE9rdytlRklLMDlYS0ttd1hpSEVYeWdEaDlmZUNZY2hFCkZ5blhDTjd0R2lySTFiRVFsRG9xK1FLQmdDM2hXWHlnbkxVdmIrOXBhYlpZZVhycmRTbGZDK3RXLzIyRktJN0gKSE1EeXhiNUpQWWlYSVJPMjZYMndjTGpjNGVRQTh0UmlTakd0a3BSelZwSzkvZS9kWjN6YnpTdS9mT1ZabTl0RgpRL1pCT2hPSXU0bHJTbU1YR2QzUU15QkpUVTMyOFZta3FoRnFnMlJTSlJrWWQzOVRheEJ0NXVEczV0blFZQjg5CkVYbTVBb0dCQU02aU5qdEdFVnVMbGo2dldXekRXVlFPVVZ2QzBLQlB3UjhJL2pnVTFQbnBud1NVYyt0ZjAyT3cKMlpPNVpWbk5odmpmU3ZWUmo3TmlHN3FnV0lmVTIzbFRpUC9LKzN4UzFIcnlya3RpU3h2UFU1WnlBWmFLeDkrWgp5UjFzdEU1UFVlMFlWRHlDdkpjWGt6enhVODhRN1hpTlB3OXgrSC95aHdlMVlqRHYwYXpOCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
  server.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwakNDQW82Z0F3SUJBZ0lVUEh6SU9FVUhnSm9QWE8zRDNZV1FoTVEvL0tBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF4TVFjMmx0Y0d4bExXRmtiV2x6YzJsdmJqQWVGdzB5TVRBek1qRXhPVEV4TURCYQpGdzB5TWpBek1qRXhPVEV4TURCYU1DY3hKVEFqQmdOVkJBTVRISE5wYlhCc1pTMWhaRzFwYzNOcGIyNHVaR1ZtCllYVnNkQzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNldXp2V2s4SVkKSHlPRFgzam1PUlVxSVpTaVIyM0g3VklCVVNQSUg2SWhJTXBGb202STlrSDJZQjFMTXd6Tk1SU09kQmhQcEx1UApJRVJkd3pWWjB3N3MxTnZ5N1dSa2lpUDJwMFlmLzlQelF6RUt5blROdGxnVFRKWkJEYkdGTklOQnRIWHlzOTBwCnh3VTRjQVAvNzlabVBGMmpNcE12SGhNclQvc2dYV3ZPK3l4MjloZGhzeVk0MlZCdy9ISDF0bzFiR0owU1ZMY0kKN1ErSHlQNWtCQ1lqMnowNEV4WHBPbEFDZTlvL2xxWSt6V240TWMzRy9xTXBmRitzWkJrMU1hSHZ5Ti85bGd2NQpyZ1BMSHByLzdYaVNRU2w5RmgwMFlGMklwZHJJSTVBcW4vcU8reUlTMUVCa24vOEN0R3hUKzNwVWVVNHg2cll2Ckp4bmVvVXlqYS9UL0FnTUJBQUdqZ2RVd2dkSXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUcKQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJEd0NnSwpyOHBkMmRWbFAyNXp1MXh0dEF3VldUQWZCZ05WSFNNRUdEQVdnQlQ2NTBXQjJTRGlpSzBQTkJ0a3QvSEVoQzF4CjdEQlRCZ05WSFJFRVREQktnaHh6YVcxd2JHVXRZV1J0YVhOemFXOXVMbVJsWm1GMWJIUXVjM1pqZ2lwemFXMXcKYkdVdFlXUnRhWE56YVc5dUxtUmxabUYxYkhRdWMzWmpMbU5zZFhOMFpYSXViRzlqWVd3d0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSmhTcHd2NEF1cFlRc0FEMzRsNDFTWGdJTHJ6R2RBQWJHU1Y5NHBrMGZwY0Y1a0JpSFRjCmJJaU1SYkJxaHMyak1pcUcwZ1QvYUpQb3NRaFdOVm1zeDM2L0M1MldNMWxOQStXQjlKMDlDaXRsRkZkZTR4Z2wKRDFXdmlTU0hray9kczVkblJKOERudUxHSHpQK1pwZTR0Mjg1dkxHSHU5NG00amxXU1hnQTJBNGMwOXNpVkgzMwowZzV5TG5TMEdrVG5YRlNLRklZV3Q4b09VS2hYby9Rb0lSa1Zrd0k0TGROcEIrTkdtOFhTQWNqSm11WlBrSVNuCjZKMmNYSk44V0VydHhraXovRmExVkYycEVDMUpkd1ZLeEIvOFdJZlhTaU9DZVZyQkhMS2g1YXhnekZUNGMvK3MKaUg1Z3pNN3YzNG91Mk5heXVTbm5DRjlCQ2pTZmdiZjU0dGM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
 name: simple-admission.default.cluster.local
webhooks:
- name: simple-admission.default.cluster.local
  clientConfig:
    service:
      name: simple-admission
      namespace: default
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lVTlowckVHbFNFMFdQVkpsWERlQ21wL21xNFJBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0d6RVpNQmNHQTFVRUF4TVFjMmx0Y0d4bExXRmtiV2x6YzJsdmJqQWVGdzB5TVRBek1qRXhPVEE0TURCYQpGdzB5TmpBek1qQXhPVEE0TURCYU1Cc3hHVEFYQmdOVkJBTVRFSE5wYlhCc1pTMWhaRzFwYzNOcGIyNHdnZ0VpCk1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRFRoWGs4Y0N5NnBlV3pwUlpqNS8rQU9YSEoKbGMxRzhuRWFTNUIvcHUxeGwxWThQVkppSGF1dVpxSjdIV21kbmhQY2w0dFRaaUNGemZWSmg1VlVDODJrMS9LZwpOdXNCcVpaWEFSMEN0Q2VHVGo4ZHpXc1cvRnMwSVpiT3ptc2NsaFF1YVdsUzEyZVNsSlBDZmpIM3RRWTFBcVYxCnlJTEdpeGFXWmhJektIdTlDTjFJTy95ZUFubnF0TnRzbjM5V3p2d0lIOTg1anpnWFl6UjNvNTIrb3VScWZ1b1UKK1hSTmRqaXA5RkoxR2pzc1YrOG1zVnRlV0lSa0NlT1lmYmcxVUZhY0ZkRDFtbkxYNldxYVJlN3ZPS09UUzhMZwpxRzg2by9tRElvRUNFQjFhY1pZUW1xVk9mMGxCL0Y2bnRtNi9Ub1pEZXpyT3lPY1pmbUsvNU40aGRjMG5BZ01CCkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUNjUwV0IyU0RpaUswUE5CdGt0L0hFaEMxeDdEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF0RENTbkd3TApBVmtMbkRGc3NlSk5YQm5PeGpJQTg5bmNSV3R2QnNPbCtmSmRyZVhVSy9mNzEvMUJkQVZwa3M0S2lCM3U3UjVlCnBOd3RLaVF6bVhLZXhEV1BWM1Fnd2RTRGJuYkFZcWk5aS9OdnNrS2xZNExOV1FFYVpNWWxvUkRzRHkxNld0cWsKRlhiYUtoZVdnZExPcEo0M01KKzBiZUZWZndQd1g1ajlEL3g4SkpuanA3WTltcTBxOVVCRFRJbVo2ZWtub2RxNQpjZDVNTWFINEhDZEcvaWJUR0diNHlKNERsekIrWDNqMFB1NWRZbFRwUytINnhvdE9tSGhxQnJKSjVhOWtUemYwClU2OWpXemtmazBDZzlwUDY4VDdtYlhUVVRNZ1RLTTV6RzJmNHVYRk1HR2c1ZkREY0I1TFlEbHJzR21PMkcrSk0KSnpPcFhhMEJsdzdlT1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - apiGroups: ["batch"]
    apiVersions: ["v1"]
    resources: ["jobs"]
    operations: ["CREATE"]
    scope: "*"
  #namespaceSelector:
  #  matchExpressions:
  #  - key: name
  #    operator: In
  #    values: ["default"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
